revert init script back to using daemon

diff --git a/scripts/cdeapp b/scripts/cdeapp
--- a/scripts/cdeapp
+++ b/scripts/cdeapp
@@ -11,62 +11,64 @@
 ## !! TODO
 ## Find a better place for node
 
-. /etc/rc.d/init.d/functions
- 
-USER="cdeuser"
- 
-DAEMON="/usr/nlm/cde/node/current/bin/node"
-ROOT_DIR="/usr/nlm/cde/code/nlm-cde"
- 
-SERVER="$ROOT_DIR/app.js"
+DAEMON_PATH="/usr/nlm/cde/code/nlm-cde"
+
+DAEMON=/usr/nlm/cde/node/current/bin/node
+DAEMONOPTS="app"
+
+NAME=cdeapp
+RUNASUSER=cdeuser
+DESC="Node Server for CDE App"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 LOG_FILE="/var/nlm/logs/app.js.log"
 
-NAME=cdeapp 
 
-LOCK_FILE="/var/run/$NAME.pid"
- 
-do_start()
-{
-        if [ ! -f "$LOCK_FILE" ] ; then
-                echo -n $"Starting $SERVER: "
-                cd $ROOT_DIR
-                runuser -l "$USER" --session-command "$DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
-                RETVAL=$?
-                echo
-                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
+case "$1" in
+start)
+	printf "%-50s" "Starting $NAME..."
+	cd $DAEMON_PATH
+	PID=`daemon  --user=$RUNASUSER $DAEMON $DAEMONOPTS >> $LOG_FILE & echo $!`
+	#echo "Saving PID" $PID " to " $PIDFILE
+        if [ -z $PID ]; then
+            printf "%s\n" "Fail"
         else
-                echo "$SERVER is locked."
-                RETVAL=1
+            echo $PID > $PIDFILE
+            printf "%s\n" "Ok"
         fi
-}
-do_stop()
-{
-       printf "%-50s" "Stopping $NAME"
-            PID=`cat $LOCK_FILE`
+;;
+status)
+        printf "%-50s" "Checking $NAME..."
+        if [ -f $PIDFILE ]; then
+            PID=`cat $PIDFILE`
+            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
+                printf "%s\n" "Process dead but pidfile exists"
+            else
+                echo "Running"
+            fi
+        else
+            printf "%s\n" "Service not running"
+        fi
+;;
+stop)
+        printf "%-50s" "Stopping $NAME"
+            PID=`cat $PIDFILE`
             cd $DAEMON_PATH
-        if [ -f $LOCK_FILE ]; then
+        if [ -f $PIDFILE ]; then
             kill -HUP $PID
             printf "%s\n" "Ok"
-            rm -f $LOCK_FILE
+            rm -f $PIDFILE
         else
             printf "%s\n" "pidfile not found"
         fi
-}
- 
-case "$1" in
-        start)
-                do_start
-                ;;
-        stop)
-                do_stop
-                ;;
-        restart)
-                do_stop
-                do_start
-                ;;
-        *)
-                echo "Usage: $0 {start|stop|restart}"
-                RETVAL=1
+;;
+
+restart)
+  	$0 stop
+  	$0 start
+;;
+
+*)
+        echo "Usage: $0 {status|start|stop|restart}"
+        exit 1
 esac
- 
-exit $RETVAL
